#+TITLE: 
#+AUTHOR:     
#+EMAIL:     
#+DATE:
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [letter,13pt]
#+OPTIONS: toc:nil num:nil
#+LATEX_HEADER: \usepackage[margin=0.25in]{geometry}
#+LATEX_HEADER: \usepackage{songs}
#+LATEX_HEADER: \renewcommand{\lyricfont}{\large} 
#+COMMENT: This generaly exported well, some quirks but it seemed to generate a reasonable printout

#+BEGIN_export latex
%\songsection{Worship Songs}
\begin{songs}{}

\beginsong{Hark the Herald Angels Sing}
\beginverse
Hark! the herald angels sing,
"Glory to the newborn King:
peace on earth, and mercy mild,
God and sinners reconciled!"
Joyful, all ye nations, rise,
join the triumph of the skies;
with th'angelic hosts proclaim,
"Christ is born in Bethlehem!"
\endverse
\beginchorus
Hark! the herald angels sing,
"Glory to the newborn King"
\endchorus
\beginverse
 Christ, by highest heaven adored,
Christ, the everlasting Lord,
late in time behold him come,
offspring of the Virgin's womb:
veiled in flesh the Godhead see;
hail th'incarnate Deity,
pleased with us in flesh to dwell,
Jesus, our Immanuel. [Refrain]
\endverse
\beginverse
Hail the heaven-born Prince of Peace!
Hail the Sun of Righteousness!
Light and life to all he brings,
risen with healing in his wings.
Mild he lays his glory by,
born that we no more may die,
born to raise us from the earth,
born to give us second birth. [Refrain]
\endverse
\endsong

\end{songs}

#+END_Export






